apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: team-tracker
    component: backend
spec:
  selector:
    app: team-tracker
    component: backend
  ports:
    - port: 3001
      targetPort: 3001
      protocol: TCP
