apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: team-tracker
  labels:
    app: team-tracker
    component: frontend
spec:
  to:
    kind: Service
    name: team-tracker
  port:
    targetPort: proxy
  tls:
    termination: reencrypt
