apiVersion: v1
kind: Service
metadata:
  name: team-tracker
  labels:
    app: team-tracker
    component: frontend
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: frontend-proxy-tls
spec:
  selector:
    app: team-tracker
    component: frontend
  ports:
    - port: 4180
      targetPort: 4180
      name: proxy
      protocol: TCP
