apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- backend-deployment.yaml
- backend-service.yaml
- backend-pvc.yaml
- frontend-deployment.yaml
- frontend-service.yaml
- frontend-route.yaml
- api-route.yaml
- serviceaccount.yaml
- cronjob-sync-refresh.yaml
- chatbot-deployment.yaml
- chatbot-service.yaml
- db-service.yaml

configMapGenerator:
- literals:
  - NODE_ENV=production
  - API_PORT=3001
  - JIRA_HOST=https://redhat.atlassian.net
  - ADMIN_EMAILS=
  - CRON_ADMIN_EMAIL=
  - CHATBOT_SERVICE_URL=http://chatbot:8002
  - DB_NAME=org-pulse
  name: team-tracker-config
- files:
  - app.conf.template=nginx-app.conf.template
  name: nginx-config-template
- literals:
  - CHATBOT_PORT=8002
  - ORG_PULSE_API_URL=http://backend:3001
  name: chatbot-config

images:
- name: quay.io/org-pulse/org-pulse-chatbot
  newTag: cc3d965e8c4e7b71d965ea7fc87ddaeeb54cd483
- name: quay.io/org-pulse/org-pulse-core-backend
  newTag: cc3d965e8c4e7b71d965ea7fc87ddaeeb54cd483
- name: quay.io/org-pulse/org-pulse-core-frontend
  newTag: cc3d965e8c4e7b71d965ea7fc87ddaeeb54cd483
