apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- backend-deployment.yaml
- backend-service.yaml
- backend-pvc.yaml
- frontend-deployment.yaml
- frontend-service.yaml
- frontend-route.yaml
- api-route.yaml
- serviceaccount.yaml
- cronjob-sync-refresh.yaml

configMapGenerator:
- literals:
  - NODE_ENV=production
  - API_PORT=3001
  - JIRA_HOST=https://redhat.atlassian.net
  - ADMIN_EMAILS=
  - CRON_ADMIN_EMAIL=
  name: team-tracker-config
- files:
  - app.conf.template=nginx-app.conf.template
  name: nginx-config-template

images:
- name: quay.io/org-pulse/org-pulse-core-backend
  newTag: 11c42c35ae1740ddc9d2ab9a4ea9948117e9b08d
- name: quay.io/org-pulse/org-pulse-core-frontend
  newTag: 11c42c35ae1740ddc9d2ab9a4ea9948117e9b08d
