- op: replace
  path: /spec/ports
  value:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
- op: add
  path: /spec/type
  value: NodePort
- op: remove
  path: /metadata/annotations/service.beta.openshift.io~1serving-cert-secret-name
